/* Day 4 -- Euclidean GCD: same algorithm as day02 gcd_01.smv and day04
 * counter.cry, in C.  Used in two CBMC modes:
 *
 *   PROPERTY mode    -- prove gcd(a,b) divides both a and b for a,b in [0..20]:
 *       cbmc gcd.c gcd_check.c --unwind 11 --unwinding-assertions
 *       expected verdict:  VERIFICATION SUCCESSFUL
 *
 *   COVERAGE / TEST-GEN mode -- ask CBMC to enumerate input pairs that
 *   exercise every BRANCH in the implementation (one concrete unit test
 *   per branch goal):
 *       cbmc gcd.c gcd_check.c --cover branch --unwind 11
 *       expected output:
 *         coverage goals: 8
 *         ** N of N covered (N%)
 *         (one SATISFIED line per branch, with concrete a, b values)
 *
 * That second mode is the unit-test generation angle: CBMC walks every
 * branch of the loop and prints a concrete input pair driving the loop
 * into that branch -- one test per coverage goal, generated by the solver.
 */
#include <assert.h>

/* Iterative Euclidean GCD over nonneg ints.  gcd(0, 0) = 0 by convention
 * (no positive common divisor); gcd(0, b) = b; gcd(a, 0) = a; otherwise
 * the loop runs until b reaches 0. */
int gcd(int a, int b)
{
    while (b != 0) {
        int t = b;
        b = a % b;
        a = t;
    }
    return a;
}
