/* CBMC harness for gcd.c -- two complementary modes.
 *
 * PROPERTY mode (default):
 *   cbmc gcd.c gcd_check.c --unwind 11 --unwinding-assertions
 *   -> VERIFICATION SUCCESSFUL: for every (a, b) in [0..20] x [0..20],
 *      the returned gcd divides both a and b (with the (0, 0) edge case
 *      handled explicitly).
 *
 * COVERAGE / TEST-GEN mode:
 *   cbmc gcd.c gcd_check.c --cover branch --unwind 11
 *   -> CBMC prints one "SATISFIED" coverage goal per branch in gcd, each
 *      with a concrete (a, b) witness -- the unit-test inputs.  Feed
 *      those (a, b) pairs into your favourite unit-test runner and you
 *      have branch-covering tests, generated by the solver instead of
 *      hand-written.
 */
#include <assert.h>

int gcd(int a, int b);

/* CBMC nondeterminism: returns an unconstrained int each call. */
int nondet_int(void);

int main(void)
{
    int a = nondet_int();
    int b = nondet_int();

    /* Keep inputs small + nonneg so the iteration count is bounded
     * (the loop runs at most log_phi(max(a,b)) times: 11 unwinds covers
     * every (a, b) with both <= 20). */
    __CPROVER_assume(a >= 0 && a <= 20);
    __CPROVER_assume(b >= 0 && b <= 20);

    int g = gcd(a, b);

    /* THE SPEC: g divides both a and b.  Encode it carefully so the
     * (0, 0) edge case (gcd = 0; "divides" is vacuous) does not divide
     * by zero. */
    if (a > 0 || b > 0) {
        assert(g > 0);                     /* gcd of (a,b) != (0,0) is positive */
        if (a > 0) assert(a % g == 0);     /* g divides a */
        if (b > 0) assert(b % g == 0);     /* g divides b */
    } else {
        assert(g == 0);                    /* gcd(0, 0) is 0 by convention */
    }

    return 0;
}
